name: Shopify performance metrics
on:
  push:
    branches: 
      - main
jobs:
  shopify_performance_data:
    runs-on: ubuntu-latest

    steps:
    # To collect data from API
    - name: Fetch data from API
      run: |
          API_URL="https://dummy.restapiexample.com/api/v1/employees"
          API_TOKEN="${{ secrets.API_TOKEN }}"
          API_RESPONSE=$(curl -s -H "Authorization: Bearer $API_TOKEN" "$API_URL")
          echo "$API_RESPONSE" > data_input.json
          cat data_input.json
          
    # Setup Python to parse json data
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies to run Python
    - name: Install dependencies
      run: pip install pandas

    # Install jq to parse json
    - name: Install jq
      run: sudo apt-get install jq -y

    # Parse json file to text file
    - name: Parse JSON using jq and save to file
      run: |
        jq '.[] | .date' data_input.json > date.txt
        jq '.[] | .sessions' data_input.json > sessions.txt
        jq '.[] | .revenue' data_input.json > revenue.txt
        jq '.[] | .orders' data_input.json > orders.txt
        jq '.[] | .conversionrate' data_input.json > conv_rate.txt
        jq '.[] | .aov' data_input.json > aov.txt
      
    # Inject data to excel sheet    
    - name: Parse JSON data
      run: python parse_data_to_excel.py parsed_data.txt

    # Upload excel file to Google sheet  
    - name: Authenticate with Google Sheets API
      run: |
        # Use OAuth2 or another authentication method to authenticate with Google Sheets API
        # Store credentials securely using GitHub Secrets

    # Install selenium for taking screenshots
    - name: Install dependencies to take screenshot
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        pip install selenium

    # Script to take screenshot
    - name: Run Python script to capture screenshot
      run: |
        python screenshot.py

    # Install slack sdk
    - name: Install slack dependencies
      run: pip install slack_sdk

    # Script to take screenshot
    - name: Send screenshot to slack channel
      run: |
        python slack_report.py
      
    # Make sure to cleanup the repo end of the session for fresh data load
    - name: Cleanup
      run: |
        # Cleanup any temporary files or resources  
